### ISSUE TITLE
export fails with multiple remotes

### ISSUE THREAD

**Issue by NikolausDemmel** [dirk-thomas/vcstool#10]
With two remotes `foo` and `bar`:
```
$ vcs export
Could not determine remote url: error: invalid key (newline): remote.foo
bar.url
```

**Comment by dirk-thomas** [comment]
Duplicate of #8.

**Comment by jbohren** [comment]
@NikolausDemmel Feel free to try out my `fix-git-multiple-remotes` branch, which handles this situation: https://github.com/jbohren-forks/vcstool/tree/fix-git-multiple-remotes
