### ISSUE TITLE
Offline tests

### ISSUE THREAD

**Issue by jayvdb** [dirk-thomas/vcstool#103]
Would be possible to have a cut down version of the test suite which uses offline data.

I'm packaging this for openSUSE https://build.opensuse.org/package/show/home:jayvdb:ros/python-vcstool , and the rpm build environment is isolated from the internet.

I can add tarballs of other repos from the tests repo.list to the build environment, and manually import them.

Ideally the test runner would recognise that the repo is already imported, and not try to update it, and then run the tests.

**Comment by dirk-thomas** [comment]
I am not sure how valuable a cut down version of the test suite would be? I would guess a reduced set will inevitably reduce coverage.

Please feel free to propose patches which would help with your use case. The only precondition I would have is that it shouldn't negatively affect the tests when run through the current CI as well as locally for a developer.

**Comment by dirk-thomas** [comment]
@jayvdb Are you interested to work on this? If yes, I am happy to keep this ticket open.

**Comment by jayvdb** [comment]
My plate is extremely full, especially at the moment due to GSoC duties, so I can not commit to doing it in the near future, but it does need to get done for distro packaging.  It is also blocking packaging of the tools which use vcstool as a dependency, generally the "future" ROS toolkit being developed.  As this package rises in importance, the need for this will increase, and people willing and able to do it also increases.

The proposed changes would not alter the existing CI.  They would only add support for the existing test suite to work correctly in distro packaging isolated VM environments, provided a limited smoke test.  Without it, distro packages bitrot because the *packaging* is not maintained, e.g. dependency changes are not noticed during version bumps.

**Comment by dirk-thomas** [comment]
@jayvdb Friendly ping.

**Comment by rotu** [comment]
Agreed. I'm trying to make tests for https://github.com/dirk-thomas/vcstool/pull/123 without adding remote web requests. I think this can be done by simply spinning up a `http.server.HTTPServer` on localhost in a parallel thread.

**Comment by dirk-thomas** [comment]
I am going to close this ticket since I don't plan to spend any time on this.

If someone would like to contribute a pull request I am more than happy to review it.
