### ISSUE TITLE
`--skip-existing` not working for entries with a version

### ISSUE THREAD

**Issue by Karsten1987** [dirk-thomas/vcstool#107]
I am unsure whether I am doing something wrong or `--skip-existing` doesn't work in a way I expect it to work.

Steps to reproduce:
```
mkdir -p ~/tmp_ws/src
cd ~/tmp_ws
wget https://gist.githubusercontent.com/Karsten1987/fcb84771fdcdb05287aaa8029569814c/raw/b0ea145c8758e7fb72682b007a3721a61559030d/rosbag2.repos
vcs import src < rosbag2.repos
cd src/rosbag2_bag_v2
git checkout -b custom_branch
cd ../../
vcs import --skip-existing src < rosbag2.repos
```

Expected behavior:
the git branch within the `rosbag2_bag_v2` repository is still on `custom_branch`.

Actual behavior:
```
 ➭ vcs import src --skip-existing < rosbag2.repos
=== src/ros2/rosbag2_bag_v2 (git) ===

Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by dirk-thomas** [comment]
Atm the option `--skip-existing` only leaves the branch untouched if the entry in the `.repos` doesn't contain a specific version (see the [description in the original PR](https://github.com/dirk-thomas/vcstool/pull/99) as well as the [actual logic](https://github.com/dirk-thomas/vcstool/blob/ab6328300970c082764d9450cec113431a29b776/vcstool/clients/git.py#L253-L279)).

We could change that logic to also skip existing - even if the entry does have a `version`: see #108.

@mxgrey FYI

**Comment by mxgrey** [comment]
I believe you can add the `--force` command if you are okay with a mismatch between the version specified in the `.repos` file versus the actual version that's currently checked out. I suggest checking if the additional `--force` command is okay for your use case.

I would recommend keeping things the way they are if `--force` is working as intended.

**Comment by dirk-thomas** [comment]
@mxgrey How would `--force` address the use case @Karsten1987 described? He wants the custom branch be untouched by the `import --skip-existing`.

**Comment by mxgrey** [comment]
Oh right sorry, I had my mental model inverted.

I guess we would need something like `--force-skip-existing` for that kind of use case.

**Comment by dirk-thomas** [comment]
> I guess we would need something like `--force-skip-existing` for that kind of use case.

Why? Does the proposed PR not work for you? If not, can you please clarify what exactly you need `import` to do?

**Comment by mxgrey** [comment]
Personally my inclination would be to exercise caution if a `.repos` file is explicitly specifying a version as being necessary and only allow flexibility if the `.repos` file is agnostic about which version to check out.

If others would prefer that `--skip-existing` should ignore the version explicitly specified in the `.repos` file by default, then I won't protest that, but I personally think it would make more sense to be more conscious about what `.repos` file you're importing, and maybe modify the `.repos` file to be version-agnostic if it's not really supposed to care about the version of the repo.

But if others disagree about what kind of behavior is desirable, then I won't try to block the change.

**Comment by dirk-thomas** [comment]
> Personally my inclination would be to exercise caution if a `.repos` file is explicitly specifying a version as being necessary and only allow flexibility if the `.repos` file is agnostic about which version to check out.

That is not the semantic of a `.repos` file. If the version if not defined for an entry that doesn't mean that it is agnostic to the version but to use the default branch of the repository.

**Comment by mxgrey** [comment]
Okay, then I guess there's nothing to block the PR on :+1:
