### ISSUE TITLE
VCS fails when connecting to unknown host via SSH

### ISSUE THREAD

**Issue by icolwell-as** [dirk-thomas/vcstool#110]
**Steps to reproduce:**

1. Create a .repos file with ssh URLS
2. Delete your `~/.ssh/known_hosts` file
3. Import the .repos file using vcs and watch the output look something like the following:

> EEEThe authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? .The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? ......

I tried typing "yes" a few times and more dots appeared, but then it hanged for quite a while and seemed to get stuck.

**Possible Solutions:**
- Add an arg to auto-accept the connection (possibly dangerous).
- Improve the user experience by presenting a (y/n) prompt that actually works.

**Comment by dirk-thomas** [comment]
By default `vcs` runs concurrent commands for all repositories therefore it can't use `stdin` / a prompt "that actually works".

Have you tried to operate on the repositories sequentially with the option `-w 1`?

**Comment by icolwell-as** [comment]
Thanks for the fast response! the `-w` option works great for my purposes! 
I didn't know `-w` existed, for anyone else who may be curious it's shown in `vcs import --help`:
```
-w N, --workers N  Number of parallel worker threads (default: 12)
```

**Comment by dirk-thomas** [comment]
> Add an arg to auto-accept the connection

Can you please verify on which native command (`git clone`?) you get the error message with the prompt to confirm the connection? And then check if it offers an option to automatically except the question.

**Comment by icolwell-as** [comment]
It was a `git clone` via ssh indeed. I believe the issue is more with ssh than git, since it's an ssh connection issue. I briefly looked over `git clone --help` but it doesn't mention anything about managing this ssh connection.

Maybe a better possible solution is to pre-check all the ssh urls in the `.repos` file and do a quick test connection to each unique host before running the git clones in parallel.
This command could work as a way to bring up the prompt if the host is not in known_hosts, but otherwise do nothing.
```
ssh -T git@github.com &> /dev/null
```

**Comment by dirk-thomas** [comment]
See #113 for a workaround. Please try the proposed change and comment if that works for your use case.
