### ISSUE TITLE
vcstool does not play nice when subtools need user interaction

### ISSUE THREAD

**Issue by rotu** [dirk-thomas/vcstool#127]
When using an unauthenticated ssh host, VCS forwards the prompt to the user but this prompt is broken:

```
$ vcs pull
The authenticity of host 'gitlab.com (2606:4700:90:0:f22e:fbec:5bed:a9b9)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
The authenticity of host 'github.com (140.82.114.3)' can't be established....E.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? .....................................................E..............................Y
Please type 'yes', 'no' or the fingerprint: yes
Please type 'yes', 'no' or the fingerprint: yes
Please type 'yes', 'no' or the fingerprint: yes
Please type 'yes', 'no' or the fingerprint: yes
Please type 'yes', 'no' or the fingerprint: 
```

**Comment by dirk-thomas** [comment]
Are you trying to run `pull` with multiple repositories expecting interactive input? If yes, please read https://github.com/dirk-thomas/vcstool#parallelization-and-stdin

**Comment by rotu** [comment]
That link seems unclear: "In the case repositories are using SSH git@ URLs but the host is not known yet vcs import automatically falls back to a single worker."

This feature seems to not work correctly with `vcs pull`.

If we don't expect it to work, maybe we should be setting  `GIT_SSH_COMMAND="ssh -o 'BatchMode=true'" `

**Comment by dirk-thomas** [comment]
> This feature seems to not work correctly with `vcs pull`.

As the comment you cited literally says "`vcs import` ..." so this isn't expected to do any magic for `vcs pull`.

The overhead to check if a host is knows isn't cheap. As of #113 it is performed for `import` since the user doesn't have the repositories yet. In your case using `pull` you already have communicated with these hosts once (assuming the working copy wasn't copied from another machine). Atm there is no check in this case of `pull` (or any of the other verbs).

Please try the option `--workers 1` as recommended in the referenced README.

> If we don't expect it to work, maybe we should be setting  `GIT_SSH_COMMAND="ssh -o 'BatchMode=true'" ` when there are multiple workers.

I doubt this is as straight forward as you describe it. What if the user already has this environment variable set?

**Comment by rotu** [comment]
> As the comment you cited literally says "`vcs import` ..." so this isn't expected to do any magic for `vcs pull`.

Oh weird. This makes the inconsistency even more glaring - I would have thought that if the problem is mentioned for one verb, it is solved for all.

> The overhead to check if a host is knows isn't cheap. As of #113 it is performed for `import` since the user doesn't have the repositories yet.

There’s no guarantee that a host doesn’t change, nor that the URL resolves to a unique host.

> I doubt this is as straight forward as you describe it. What if the user already has this environment variable set?

If it’s already set, you can append ` -o BatchMode=true` to the existing value.

But this does seem a somewhat lazy fix. A more ideal fix would be not to interleave subprocess IO in the first place but to buffer separately and, if a subprocess does not terminate in a timely manner, hook up its IO to `vcstools` streams.

**Comment by dirk-thomas** [comment]
> if a subprocess does not terminate in a timely manner, hook up its IO to `vcs` streams and stop launching new workers until it does terminate.

That sounds like a very fragile heuristic which I don't think is the right way to implement a fix. At the moment the user will notice the problem and can then re-run the command with a single worker.

If anyone has other proposals how to resolve this differently I am happy to consider implementing them.

**Comment by rotu** [comment]
It actually doesn't seem fragile at all in concept! The "terminate in a timely manner" is not actually needed.

The algorithm I had in mind is as follows:

While there is still work to do:
1. If fewer worker subprocesses than desired are running, launch a new worker.
2. If there is a worker subprocess hooked up to IO, and that subprocess has terminated, flush all buffered data and disconnect it.
3. If there is *not* a worker subprocess hooked up to IO, pick the first live worker subprocess. Hook its output up to stdout / stderr and its input up to stdin.

This has the bonus that subprocesses would also not have their output interleaved.

I tried to code it up but the implementation got hairier than I expected so I gave it up. Here were the two big hurdles:

1. Multiplexing stdin to several subprocesses involves creating a reader thread just to service stdin or using asyncio. (I could use `select` to detect whether there was stdin available, but then I have to figure out a solution for Windows as well)
2. I wasn't sure if git would play nice even if I did the above. It seems that ssh [does something funky with io](https://unix.stackexchange.com/questions/171835/how-does-ssh-prompt-for-a-password-when-all-input-and-output-is-redirected) so I might have needed to use a pseudoterminal or some other dark magic.

**Comment by dirk-thomas** [comment]
> It actually doesn't seem fragile at all in concept! One might say "the user will notice and know what to do" is a more fragile heuristic :-p.

Can you please describe how the following simple example would work with your algorithm:

* Two repositories are being processed concurrently and are running "long".
* No output is shown yet since they shouldn't interleave.
* At what point should stdin be directed to one of the processes? Obviously the user would need to see the output of that process in order to know what to input.
* At the moment all output is shown in alphabetical order. Are you suggesting to fundamentally change when and what the tool outputs?

**Comment by rotu** [comment]
> Can you please describe how the following simple example would work with your algorithm:
> 
> * Two repositories are being processed concurrently and are running "long".
> * No output is shown yet since they shouldn't interleave.
> * At what point should stdin be directed to one of the processes? Obviously the user would need to see the output of that process in order to know what to input.

As soon as possible. You don't need user interaction to *start* a subprocess, you just might need it to *end* that subprocess. If repos A and B are both running long, IO is hooked up to process A until it terminates. Process B's output goes to a buffer. When process A finally terminates, the buffered output from process B is presented to the user and user input is directed to process B.

> * At the moment all output is shown in alphabetical order. Are you suggesting to fundamentally change when and what the tool outputs?

The order doesn't matter. You can still do it alphabetical order, the order in the YAML file, or any other order you like. The key point is that user interaction (both input and output) is treated as a non-shared resource available to at most one subprocess at a time that stays with that subprocess until it finishes.

**Comment by dirk-thomas** [comment]
> Are you suggesting to fundamentally change when and what the tool outputs?

The implicit answer to this question is: yes, the output of one process (the one owith IO hooked up) needs to be streamed. Also the progress indicator can't be shown anymore.

Please consider to contribute a pull request. Assuming that the changes will be quite significant it might make sense to first describe the proposed changes for initial feedback.

**Comment by rotu** [comment]
> The implicit answer to this question is: yes, the output of one process (the one owith IO hooked up) needs to be streamed. Also the progress indicator can't be shown anymore.

I'm still not quite sure if I understand. The output of the tool should be unchanged - the only difference is in the timing of output when there are multiple processes.

The progress indicator can also be shown as well - it might make sense to buffer it though, so it doesn't interfere with program interaction flow as below:

```
The authenticity of host 'gitlab.com (2606:4700:90:0:f22e:fbec:5bed:a9b9)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
The authenticity of host 'github.com (140.82.114.3)' can't be established....E.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? ................
```

> Please consider to contribute a pull request. 

I tried and maybe I'll give it another crack in a while. These were the issues I encountered the first time I tried:

> I tried to code it up but the implementation got hairier than I expected so I gave it up. Here were the two big hurdles:
> 
> 1. Multiplexing stdin to several subprocesses involves creating a reader thread just to service stdin or using asyncio. (I could use `select` to detect whether there was stdin available, but then I have to figure out a solution for Windows as well)
> 2. I wasn't sure if git would play nice even if I did the above. It seems that ssh [does something funky with io](https://unix.stackexchange.com/questions/171835/how-does-ssh-prompt-for-a-password-when-all-input-and-output-is-redirected) so I might have needed to use a pseudoterminal or some other dark magic.

**Comment by dirk-thomas** [comment]
> The progress indicator can also be shown as well - it might make sense to buffer it though, so it doesn't interfere with program interaction flow as below:

So the current progress indicator can *not* be used as is as you notices with the interleaved output. Obviously a completely different progress indicator could be implemented.

**Comment by dirk-thomas** [comment]
I am going to close this ticket since I don't plan to spend any time on this feature. Imo using a single worker is sufficient for this corner case.

If anyone would contribute a pull request I am happy to review it.
