### ISSUE TITLE
import --force is broken on Windows

### ISSUE THREAD

**Issue by rotu** [dirk-thomas/vcstool#130]
`vcs import --force` fails with a PermissionError on Windows.
This is because git creates its index files with the readonly flag, which must be cleared before the file can be deleted.

```Invocation of command 'import' on client 'git' failed: PermissionError: [WinError 5] Access is denied: 'src/eProsima/Fast-CDR' (c:\python37\lib\site-packages\vcstool\clients\git.py:242)```

https://github.com/ros2/rmw_cyclonedds/pull/168/checks?check_run_id=627448665#step:4:430

**Comment by dirk-thomas** [comment]
Thanks for the report. The problem has been addressed in #134.
