### ISSUE TITLE
[feature] --skip-repos option to skip one or more listed repositories during import

### ISSUE THREAD

**Issue by eliasdc** [dirk-thomas/vcstool#135]
I'm using `vcs import src < repos.txt` for a ROS workspace to pull in dependencies. I would like to have a feature where I can skip one or more repositories.

The reason for this feature is when you're building a docker image and use the import you could skip a folder which is already in your workspace (same repo but for example without a `.git` folder). `--skip-existing` could be used if there was an additional parameter to even ignore different url (in CI/CD the for the current directory can be different).

**Comment by dirk-thomas** [comment]
Am I assuming correctly that using `--skip-existing` already achieves the desired behavior? And the only inconvenience is that the tool will return an error code and a message like this for the existing non-git directory?

> Could not clone repository '<URL>': fatal: destination path '.' already exists and is not an empty directory.

To address this #136 changes the behavior to not result in a return code and print the following message instead:

> Skipped existing directory

**Comment by eliasdc** [comment]
That was indeed the behavior I was getting and with your comment, that it is just an error code, I fixed my dockerfile by appending `|| true` but this means that I ignore all errors from vcs (auth errors, etc.). 

Thanks for looking into it so quickly.

**Comment by dirk-thomas** [comment]
Can you try using the branch of the referenced PR in your Docker file (without the `|| true`) to confirm it works for you as desired?

**Comment by eliasdc** [comment]
It did not work. It skipped every entry. In the below example only src/repo1 is a custom folder with some content:
```
#15 13.15 === src/repo1 (git) ===
#15 13.15 Skipped existing directory
#15 13.15 === src/repo2 (git) ===
#15 13.15 Skipped existing directory
#15 13.15 === src/sensors/ros2_intel_realsense (git) ===
#15 13.15 Skipped existing directory
#15 13.15 === src/sensors/sick_safetyscanners (git) ===
#15 13.15 Skipped existing directory
```
An other reason for the `--skip-repos` is if you want to skip downloading a specific repository entirely.  This way it would be possible to first get all other repositories install the dependencies of those and later in a next step copy the workspace into docker image.

**Comment by dirk-thomas** [comment]
> It did not work.

Sorry, looking at my own patch I don't know what I was thinking... I updated the branch and would appreciate if you could give it another try. Thanks.

**Comment by eliasdc** [comment]
same problem. I think those folders are created before the clone (but empty which works for a clone) so the path always exists.

**Comment by dirk-thomas** [comment]
This time I took the time to reproduce your use case (which I should have done in the first place) and I think I got it right. Thanks for your patience and hoping you can try it again.

**Comment by eliasdc** [comment]
This time it did work, thanks.
```
#15 18.44 === src/repo1 (git) ===
#15 18.44 Skipped existing directory
#15 18.44 === src/repo2 (git) ===
#15 18.44 Cloning into '.'...
#15 18.44 === src/sensors/sensorA (git) ===
#15 18.44 Cloning into '.'...
#15 18.44 Switched to a new branch 'refactor'
#15 18.44 Branch 'refactor' set up to track remote branch 'test' from 'origin'.
#15 18.44 === src/sensors/sensorB (git) ===
#15 18.44 Cloning into '.'...
#15 18.44 Switched to a new branch 'test'
```
