### ISSUE TITLE
apt install python-vcstool version error

### ISSUE THREAD

**Issue by jdott** [dirk-thomas/vcstool#141]
Just checking with you guys. I found when trying to run the install of vcstool with: 
sudo apt install python-vcstool 

I would get a version error claiming my python version was out of range 

The following packages have unmet dependencies:
 python-vcstool : Depends: python2 (< 2.8) but it is not installable
                  Depends: python2 (>= 2.7) but it is not installable
                  Depends: python2:any (>= 2.6.6-7~) but it is not installable

I do have 2.7.17, but looking into this further I checked the ros package list here:
http://packages.ros.org/ros/ubuntu/dists/bionic/main/binary-amd64/Packages 

It seems for python-vcstool it checks for the version using python2 vs python. Not sure if this was used due to conflicts with python3 but it seems to fail the check and would think just using python instead of python2 would be correct. If I am wrong, is this an issue with python2 not returning the correct version or being linked correctly? Every version check on several machines return the right 2.7.17, but all give the same error.

**Comment by dirk-thomas** [comment]
What certain of `vcstool` are you trying to install?

**Comment by jdott** [comment]
The latest version, 0.2.8

**Comment by dirk-thomas** [comment]
Thanks for the report. I guess this is due to packaging being done on Focal which uses `python2` instead of `python`. I will create a new `deb` soon to are the problem.

Until then (or even in general) you can use the Python 3 version of the package: `python3-vcstool`.

**Comment by jdott** [comment]
Okay great, thanks for the help!
