### ISSUE TITLE
Failure assertion tests are wrong

### ISSUE THREAD

**Issue by christophebedard** [dirk-thomas/vcstool#149]
`test_reimport` and `test_reimport_failed` both check that a command fails by relying on an `assert False` line.

However, expecting a failure, they both catch `BaseException`, which is the [base of all exceptions](https://docs.python.org/3/library/exceptions.html#exception-hierarchy). Therefore, if the command unexpectedly doesn't fail, it isn't detected.

For example, running this:

```python
def should_raise():
    # Does not raise
    pass

try:
    should_raise()
    assert False, 'should have failed'
except BaseException:
    print('all good')
```

outputs this:

```
all good
```

In the case of `test_reimport` and `test_reimport_failed`, the tests seem to fail if I replace `BaseException` with `subprocess.CalledProcessError`, which is the exception that should be thrown if the command fails. Therefore I'd like to get a confirmation before I try to fix the tests.

**Comment by dirk-thomas** [comment]
Thanks for reporting this. The logic in the test is certainly wrong. I think before #135 it was actually expecting a non-zero return code. But since that change the command should actually not fail. Please see #152.
