### ISSUE TITLE
Improve error message when executable is not available

### ISSUE THREAD

**Issue by shreyasr89** [dirk-thomas/vcstool#16]
=== /home/hiya/ros2_ws/src/ament/ament_cmake (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ament/ament_lint (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ament/ament_package (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ament/ament_tools (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ament/osrf_pycommon (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ament/uncrustify (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/examples (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/launch (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rcl (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rcl_interfaces (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rclc (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rclcpp (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rmw (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rmw_connext (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rmw_implementation (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rmw_opensplice (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rosidl (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)
=== /home/hiya/ros2_ws/src/ros2/rosidl_dds (git) ===
Invocation of command 'import' on client 'git' failed: TypeError: sequence item 0: expected str instance, NoneType found (/usr/lib/python3/dist-packages/vcstool/clients/vcs_base.py:51)

I am using Ubuntu 14.04 LTS.

**Comment by dirk-thomas** [comment]
Please include more information to your bug report:
* what version of `vcstool` are you using? If it is not the latest (0.1.13) please update and try again.
* what are the exact commands you are executing? Since you use the `import` command also include the yaml file you are trying to import

**Comment by shreyasr89** [comment]
Hello,

I solved that. I am at the testing and running stage. Can you please tell
me the exact steps to run files after building them?

**Comment by dirk-thomas** [comment]
Please close tickets if you managed to solve them on your own - preferably with a comment how to provide information to future readers.

Your other questions is not related to vcstool. Please post your questions at the appropriate location.

**Comment by shreyasr89** [comment]
Solved it by installing git.
sudo apt-get install git.

**Comment by dirk-thomas** [comment]
Can you please provide the version number of vcstool you are using? It should not fail in the way you posted when missing one of the vcs clients.

**Comment by shreyasr89** [comment]
I am using vcs 0.1.13. I got the same problem on two systems and I solved
it by installing git client.

**Comment by dirk-thomas** [comment]
The error message is indeed not very helpful. Reopening...

**Comment by dirk-thomas** [comment]
Fix released in version 0.1.14.
