### ISSUE TITLE
"vcs log" optionally only show merge commits

### ISSUE THREAD

**Issue by 130s** [dirk-thomas/vcstool#174]
# Problems

`vcs log` particularly with `--limit*` options is so convenient for release maintenance (and also to communicate with non-development teams). Thanks!

Problem I want to raise is that unless either/both commit message is well-formatted and/or the chunk of commits is well-aggregated, the command can show too many commits with less meaningful descriptions.

This is **not** the tool's fault per se. But I feel like there's a room for the tool to provide a mitigating option.

**Comment by 130s** [comment]
What I found really working fine at my work is to only reference the merge commits (proven in https://github.com/ros-infrastructure/catkin_pkg/pull/297).

If adding such an option to `vcs log` makes sense, I'm happy to provide PR.

**Comment by dirk-thomas** [comment]
> show many meaningless commit messages

I would definitely agree that this statement is only true if you do many commits with meaningless commit messages.

That being said a new option like `log --merge-only` would be great to have. A pull request would certainly be appreciated.

**Comment by dirk-thomas** [comment]
Implemented in #194.
