### ISSUE TITLE
vcstool doesn't take uri as import option

### ISSUE THREAD

**Issue by kodyensley** [dirk-thomas/vcstool#18]
wstool supported the notion of using a uri to pull down a remote rosinstall file. It seems that vcstool should support taking a local file or pulling down a remote yaml file for the import command.

**Comment by dirk-thomas** [comment]
As for many other linux commands this is already possible by piping the output of one command to another. You can e.g. call the following `wget -O - http://example.com/some.rosinstall | vcs import path`.

Using this approach you can leverage all the possibilities existing tools already provide: username / password or certificates, proxy support, handling of redirects, trust server certificates, various protocols. A custom implementation would probably never provide the flexibility already available in tools like `wget`.

Therefore I don't plan to add this as a part of `vcstool`.
