### ISSUE TITLE
multiple passworded HTTPS repos causes errors 

### ISSUE THREAD

**Issue by LukeAI** [dirk-thomas/vcstool#197]
I have a repos file containing 5 HTTPS git URLs for private repos. When I run import:

```
$ vcs import < myrepos.repos
Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com':
```
I type: `MYUSERNAME`

and I get:
```
Password for 'https://MYUSERNAME@github.com':
```

I type: `MYPASSWORD` and get prompted 4 more times, with the password shown in the URL and then vcs hangs forever.
```
Password for 'https://MYPASSWORD@github.com': Password for 'https://MYPASSWORD@github.com': Password for 'https://MYPASSWORDy@github.com': Password for 'https://MYPASSWORD@github.com':
.
```
git version 2.29.2
git version 2.29.2
Ubuntu 18.04

**Comment by dirk-thomas** [comment]
Have you tried the `--workers` option described in the readme? https://github.com/dirk-thomas/vcstool

You could also configure git to not require you to interactively enter the credentials every time.
