### ISSUE TITLE
please advertise the tool

### ISSUE THREAD

**Issue by vrabaud** [dirk-thomas/vcstool#2]
I know you sent an email to ros users but please add a tiny page on the ROS wiki. Thx, it's awesome.

**Comment by 130s** [comment]
Just a comment, not requesting any action.

I was wondering how I would've missed an announcement of `vcstool`. I can't find it.

Since it's official vcs tool recommendation in ROS2 (right?) I think it's well-known already so that there may not be a need for advertisement. I'm not sure.
