### ISSUE TITLE
Cannot export all my repos

### ISSUE THREAD

**Issue by jvgomez** [dirk-thomas/vcstool#20]
Hi, I am trying to use vcstool to export the repository states to a file. All the repos share the same folder, so that I run ` vcs export > repos.cfg` and the output is almost OK:

folderA/repo1: Could not determine ref: fatal: No upstream configured for branch 'branch1'
folderB/repo2:: Could not determine ref: fatal: No upstream configured for branch 'branch2'

The configuration for these repos and the others are exactly the same (non of them have an upstream remote, but a origin). Why does this error exactly mean ?

**Comment by dirk-thomas** [comment]
Your branches `branch1` / `branch2` are likely not tracking a remote branch. I assume you can't call `git pull` for those successfully either. Can you confirm this?

This can happen if you have create the branches only locally or only pushed them to `origin` or `upstream`with `-u`. If this is the case `git` does not know which remote branch you local branch is associated to and therefore `vcstool` can't generate a url / version for it.

**Comment by jvgomez** [comment]
Hi Dirk,

Both repos have the origin remote properly set (I regularly pull). These branches are created with `git checkout -b` and then I push them (usually without the -u option), but I can do git pull origin branchX in all cases.

However, you are right :) After doing `git push -u origin branchX` I got the message
` Branch X set up to track remote branch X from origin.
Everything up-to-date`

And now there it no warning (it is surprising that my other repos are working, I never do the -u!). Thank you so much!

**Comment by NikolausDemmel** [comment]
@jvgomez just as a note: On recent `git` versions, if you check out a remote branch as a local branch for the first time using `git checkout my-branch` (which works as long as `my-branch` is unique among your remotes), then the local branch is set up to be tracking automagically.

**Comment by jvgomez** [comment]
I see, and now everything makes sense, thank you @NikolausDemmel !
