### ISSUE TITLE
Why multithreading?

### ISSUE THREAD

**Issue by frederico-klein** [dirk-thomas/vcstool#200]
Simple suggestion, since you've change the name of the executable, it would be nice if the [vcstool ROS wiki page](http://wiki.ros.org/vcstool) was updated as well. I would do it but I am not whitelisted AND I am not sure I should do it either. 

And now to the main issue. 

When I was trying to automate a docker ROS 1 build using vcs (since wstool is deprecated) and I found out that often some repos would time out. I think I was hitting bandwidth limitations because vcs was trying to download from multiple repositories all at once. 

In any case, it was annoying to debug and I think setting `--workers 1` helped, but I am not sure. It could just be completely random. In any case I am questioning the multithreading implementation as default here and if it is even necessary at all. I mean, the downloads in a series will just complete each of them faster and in the end the time it takes will be the same. This would only make sense if the repositories themselves have a bottleneck, but I think, unless someone is hosting a git repository in their home, this is not very likely.

Anyway, just my 2 cents. Close this if you know better. Cheers!

**Comment by dirk-thomas** [comment]
> Simple suggestion, since you've change the name of the executable, it would be nice if the vcstool ROS wiki page was updated as well.

Done in http://wiki.ros.org/action/diff/vcstool?action=diff&rev1=2&rev2=3

> the downloads in a series will just complete each of them faster and in the end the time it takes will be the same.

I doubt that this description matches reality. I would need to see some real world benchmarks in different environments (small/high bandwidth connectivity, small/large repos, low/high number of repositories, etc.)

I will go ahead an close the issue for now. Please feel free to provide the requested information and this can be reconsidered. Thanks.

**Comment by frederico-klein** [comment]
>I doubt that this description matches reality.

This is what happened in my environment. Known bad internet connection. I had to do get things manually because this tool kept breaking, but I suppose if other people aren't complaining there is no need to fix it anyway.
