### ISSUE TITLE
Add --repos-posix option to force POSIX paths

### ISSUE THREAD

**Issue by christophebedard** [dirk-thomas/vcstool#202]
This is a feature request. I'd be happy to open a PR after getting an OK.

In some cases, on Windows, users might have to work with POSIX paths (i.e. provide POSIX paths and expect POSIX paths). However, providing a POSIX path (as a base path) on Windows results in paths with a POSIX/Windows mix. For example:

```
$ vcs diff src/ -s --repos
src/ament\ament_cmake (git)
...
```

This is annoying to have to deal with if we intend to pipe the resulting paths into something else. For a concrete example, see https://github.com/ros-tooling/action-ros-ci/issues/578.

Therefore I am proposing to add a `--repos-posix` option (as a common argument) that would be just like `--repos` but converting repo paths to POSIX paths.

Something like:

```diff
diff --git a/vcstool/executor.py b/vcstool/executor.py
index 9b0b301..ea36a1f 100644
--- a/vcstool/executor.py
+++ b/vcstool/executor.py
@@ -1,4 +1,5 @@
 import logging
+import pathlib
 import os
 from queue import Empty, Queue
 import sys
@@ -9,12 +10,13 @@ logger = logging.getLogger(__name__)
 logging.basicConfig()


-def output_repositories(clients):
+def output_repositories(clients, force_posix=False):
     from vcstool.streams import stdout
     ordered_clients = {client.path: client for client in clients}
     for k in sorted(ordered_clients.keys()):
         client = ordered_clients[k]
-        print('%s (%s)' % (k, client.__class__.type), file=stdout)
+        path = pathlib.Path(k).as_posix() if force_posix else k
+        print('%s (%s)' % (path, client.__class__.type), file=stdout)


 def generate_jobs(clients, command):
```

A more "global" alternative could be a `--posix` option that would affect paths printed by both `output_repositories()` (for `--repos`) and `output_result()`/`output_results()`.

**Comment by dirk-thomas** [comment]
I get the problem with mixed-style paths. Instead of adding an option to control the behavior I would prefer an approach which determines what to do based on the input / environment. No new options means nothing to document / teach to users :wink: Any pull request towards supporting this would be welcome.

**Comment by christophebedard** [comment]
> Instead of adding an option to control the behavior I would prefer an approach which determines what to do based on the input / environment. No new options means nothing to document / teach to users wink

Fair point! I'll look into it.
