### ISSUE TITLE
`vcs import` and `vcs validate` are inconsistent

### ISSUE THREAD

**Issue by eduidl** [dirk-thomas/vcstool#207]
Exit codes of `vcs validate` and `vcs import` are inconsistent when the branch which does not exist is specified.

## Reproduction procedure

```
$ cat test.repos
repositories:
  vcstool:
    type: git
    url: git@github.com:dirk-thomas/vcstool.git
    version: not-found
$ vcs validate < test.repos 
=== vcstool (git) ===
Found git repository 'git@github.com:dirk-thomas/vcstool.git' but unable to verify non-branch / non-tag ref 'not-found' without cloning the repo
$ echo $?
0
$ vcs import . < test.repos 
=== ./vcstool (git) ===
Could not checkout ref 'not-found': fatal: invalid reference: not-found
$ echo $?
1
```

**Comment by dirk-thomas** [comment]
As the messages indicates `validate` can't determine if the branch name is valid without querying the repo (which it is not doing). Therefore that command can't return an error since the information is unknown.

**Comment by eduidl** [comment]
Thanks. 

Judged by the following behavior, I thought whether branch exists or not have been distinguished already. Is it wrong?
Is there any edge cases when it does not work?

```
$ cat test.repos
repositories:
  vcstool:
    type: git
    url: git@github.com:dirk-thomas/vcstool.git
    version: not-found
  default_branch:
    type: git
    url: git@github.com:dirk-thomas/vcstool.git
    version: master
  exist_branch:
    type: git
    url: git@github.com:dirk-thomas/vcstool.git
    version: 0.2.x
$ vcs validate < test.repos
...
=== default_branch (git) ===
Found git repository 'git@github.com:dirk-thomas/vcstool.git' with ref 'master'
=== exist_branch (git) ===
Found git repository 'git@github.com:dirk-thomas/vcstool.git' with ref '0.2.x'
=== vcstool (git) ===
Found git repository 'git@github.com:dirk-thomas/vcstool.git' but unable to verify non-branch / non-tag ref 'not-found' without cloning the repo
```

**Comment by dirk-thomas** [comment]
> Judged by the following behavior, I thought whether branch exists or not have been distinguished already.

Can you please be more specific what exactly in the output leads you to believe that?

**Comment by dirk-thomas** [comment]
@eduidl Friendly ping.

**Comment by eduidl** [comment]
Excuse me for late reply.

First, from the following message, we can see that the message is clearly different when the branch is present and when it is not.

```
=== default_branch (git) ===
Found git repository 'git@github.com:dirk-thomas/vcstool.git' with ref 'master'
=== exist_branch (git) ===
Found git repository 'git@github.com:dirk-thomas/vcstool.git' with ref '0.2.x'
=== vcstool (git) ===
Found git repository 'git@github.com:dirk-thomas/vcstool.git' but unable to verify non-branch / non-tag ref 'not-found' without cloning the repo
```

Second, a list of branches or tags is technically obtainable without cloning.

```terminal
$ git ls-remote git@github.com:dirk-thomas/vcstool.git
89bbf6168680a41af2367a30c8b7e42caf81cdb9	HEAD
d12093397d5ad62403013f8642294a2788d260e9	refs/heads/0.2.x
89bbf6168680a41af2367a30c8b7e42caf81cdb9	refs/heads/master
:
```

**Comment by dirk-thomas** [comment]
> a list of branches or tags is technically obtainable without cloning.

The point of the current message is that the `version` is neither a branch nor a tag. And therefore can't be checked without cloning the repository.

**Comment by eduidl** [comment]
I see. I misunderstood.
