### ISSUE TITLE
vcstool cannot be used with ssh repositories with passphrase for the identity file

### ISSUE THREAD

**Issue by galou** [dirk-thomas/vcstool#212]
Either there is a problem with my configuration or vcstool cannot be used with ssh repositories with passphrase for the identity file. I have such a repository and when I used `vcs import < my.repos`, I see the prompt `Enter passphrase for key '....':`, I then type my passphrase but see `EEE` and then I'm asked for a password, as then happens when the passphrase is incorrect.

`vcs import --input my.repos` doesn't help.

**Comment by galou** [comment]
Maybe related to #128 ?

**Comment by christophebedard** [comment]
Not sure about #128, but look at #23 and #124. There is a solution/workaround documented here: https://github.com/dirk-thomas/vcstool/blob/master/README.rst#parallelization-and-stdin. Just use `--workers 1` so that you can enter a password.

**Comment by christophebedard** [comment]
I see! That feature seems to be in >=0.2.5 so if it wasn't working for you then it might be a bug.

Looks like it's simply running `ssh-keygen -F $HOST` (e.g., `ssh-keygen -F github.com`) for all hosts and if one of the return codes is non-zero (unknown host) then it uses 1 worker. Maybe all the hosts are known on your machine?

**Comment by galou** [comment]
All the hosts should be known but their access requires giving a passphrase, which doesn't work with multiple workers. I cannot test the workaround but I guess it works, thanks!
