### ISSUE TITLE
import command changes commits when the specified version is 000000000000

### ISSUE THREAD

**Issue by pele1410** [dirk-thomas/vcstool#213]
If I have a repository defined in the yaml file with "000000000000" as the version, running the import command will move my commit to commit id 0 (1st commit).

```
fooRepo:
type: hg
url: /some/path
version: 000000000000
```

Before running `vcs import`
```
[fooRepo]$ hg id
000000000000
[fooRepo]$ hg glog
o  changeset:   1:24e45889a941
|  user:        Some Dev <some.dev@email.com>
|  date:        Mon Oct 12 11:24:13 2020 -0500
|  summary:     Some Changes
|
o  changeset:   0:d331cf556a70
   user:        Some Dev <some.dev@email.com>
   date:        Mon Oct 12 11:06:14 2020 -0500
   summary:     Initial commit
```

and after
```
[fooRepo]$ hg id
d331cf556a70
[fooRepo]$ hg glog
o  changeset:   1:24e45889a941
|  user:        Some Dev <some.dev@email.com>
|  date:        Mon Oct 12 11:24:13 2020 -0500
|  summary:     Some Changes
|
@  changeset:   0:d331cf556a70
   user:        Some Dev <some.dev@email.com>
   date:        Mon Oct 12 11:06:14 2020 -0500
   summary:     Initial commit
```

The result of running `vcs import <manifest.yaml` is
```
=== ./someRepo (hg) ===
pulling from /some/path/someRepo
searching for changes
no changes found
16 files updated, 0 files merged, 0 files removed, 0 files unresolved
```

It does not seem to matter if there are any commits pulled during the import.
If I use any other hash, the import command leaves the repository on that specific commit.  Only "000000000000" seems to not function properly.

We are using vcs v0.2.15 with Mercurial v4.6.1

**Comment by christophebedard** [comment]
I personally don't know much about hg, so I might be missing something, but I think this might be a YAML "issue"/behaviour.

For example, `version: 000000000000` gets parsed/interpreted as `0` while `version: 97c468298911` results in `97c468298911`.

However, `version: '000000000000'` correctly results in `000000000000`. Can you try adding quotes (either single or double) around it and see if that works?

**Comment by pele1410** [comment]
```
fooRepo:
type: hg
url: /some/path
version: '000000000000'
```

This worked for me, thanks!
