### ISSUE TITLE
[question]Options for updating the .rosinstall file

### ISSUE THREAD

**Issue by nicolaje** [dirk-thomas/vcstool#217]
Hello, thank you for this tool.

After I vcs imported a .rosinstall file, worked on the different repositories in the workspace, committed & pushed the changes, what would be the best way to update the .rosinstall file to reflect these changes ?

Currently I do vcs export then compare each entry in the output file to the entries in the original .rosinstall file, and update it manually.

Is there a way to automate this with vcstool, and if not is this of interest ?

**Comment by asherikov** [comment]
1. if you want to use vcstool then you should switch from rosinstall to vcstool format.
2. if you want to keep using rosinstall files, then the best bet would be to switch to wstool which supports them natively.

**Comment by dirk-thomas** [comment]
`vcstool` only supports the .rosinstall file format for backward compatibility. The format itself has some flaws (like potentially colliding entries) and therefore `vcstool` chose to use its own format in `.repos` files. Only that format is fully supported (and can therefore be written by `vcs export`).
