### ISSUE TITLE
python-vcstool is not in the Ubuntu apt server

### ISSUE THREAD

**Issue by dotjairo** [dirk-thomas/vcstool#22]
The `python-vcstool` debian package is located in the ROS apt server. [Here](http://packages.ros.org/ros/ubuntu/dists/trusty/main/binary-amd64/Packages), for example.

Adding instructions in the README to add the ROS apt server would reduce confusion when attempting to install on a vanilla Ubuntu installation, i.e. per http://wiki.ros.org/indigo/Installation/Ubuntu

```bash
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xB01FA116
sudo apt-get update
```

**Comment by dirk-thomas** [comment]
Thank you for the feedback. I have added these information to the install instructions: 0cabe6c5b4368bec7d4fcc9a7a3f14228451b128
