### ISSUE TITLE
Question: vcstool versus git submodules?

### ISSUE THREAD

**Issue by Bart-van-Ingen** [dirk-thomas/vcstool#221]
I have two questions, the answers of which I have been unable to find online: 

1. What is the difference between vcstool and using git submodules?

2. What are the advantage of vcstool over git submodules?

**Comment by christophebedard** [comment]
The answer to both questions, in short, is: git submodules are very often a pain to work with.

If you're using a git submodule and never (or very very rarely) update it (i.e. updating the commit it points to), then it's not too bad. However, if you're updating it somewhat often, it becomes a bit of a pain. It's much easier with vcstool: you either `vcs pull` (to pull new commits if your `.repos` file is tracking branches for your repos) or you simply update your `.repos` file (if your `.repos` file is tracking specific branches or commits), which is just a simple text file.

Also, in some cases, you may simply want to combine repos without necessarily involving a git repo. If you want to share/define a specific complex workspace (i.e. a set of git repos), you can do it with a simple text file (and you can use `vcs export`). No need to create a git repo just to have a bunch of submodules.

Another reason is that vcstool supports more than just git: hg, svn, bzr, and even zip and tar (https://github.com/dirk-thomas/vcstool#which-vcs-types-are-supported). It also has very handy commands to manage your set of repos (`vcs pull`, `vcs log`, `vcs diff`, `vcs status`, etc.).

I'm sure there are other reasons.

**Comment by Bart-van-Ingen** [comment]
makes sense! thanks for taking the time to answer!
