### ISSUE TITLE
`vcs status` only gives status info for top level git repo.

### ISSUE THREAD

**Issue by LukeAI** [dirk-thomas/vcstool#222]
I have a meta-repo that just contains a vcs .repos file with a list of subrepos/tags. I'd like to be able to run `vcs branch`, `vcs status` etc. to check the state of all the subrepos but I only get the git status of the top level meta-repo. I'd consider this a bug, but maybe there is some rational? Is there some way to see what I want to see?

**Comment by christophebedard** [comment]
Where do you clone/import the subrepos? Do you import them *into* the directory of your meta-repo? Then `--nested` option is probably what you want. Otherwise, just clone your repos outside your meta-repo.

**Comment by LukeAI** [comment]
ok yeah, nested does the trick. for my particular case, --nested would be preferable default behaviour - but maybe sometimes you don't want that?

**Comment by christophebedard** [comment]
There is a reason/explanation given here: https://github.com/dirk-thomas/vcstool/pull/58

> Since the crawling for potentially nested repos might inflict a significant overhead it is better to require an explicit option.

**Comment by LukeAI** [comment]
hmm, I guess I disagree but fair enough
