### ISSUE TITLE
keyserver timeout

### ISSUE THREAD

**Issue by LukeAI** [dirk-thomas/vcstool#224]
keyserver appears to be down?

when I run `sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xAB17C654` it just hangs until `gpg: keyserver receive failed: No name`

**Comment by christophebedard** [comment]
Does this work?

```sh
$ sudo apt install curl # if you haven't already installed curl
$ curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
```

**Comment by LukeAI** [comment]
yes that works.
