### ISSUE TITLE
vcs import fails when credentials are needed

### ISSUE THREAD

**Issue by daphreak** [dirk-thomas/vcstool#23]
Running `vcs import` with a config file that contains two or more repos that need either:

* http login credentials
* private key password

does not work as the prompts clobber each other.

Running `0.1.15` from PyPI

**Comment by dirk-thomas** [comment]
`vcstool` is currently not designed to provide `stdin` to any of the commands executed. Simply because I don't have a use case for this.

I am not sure how much effort it would be to implement support for user input. I would be happy to review a pull request for this.

**Comment by daphreak** [comment]
Understood. Good to know this is expected behavior.

It is certainly not an easy problem. Just piping `stdin` in from the user wouldn't be exceptionally useful because you would still have to enter credentials for each repo every time.

For now I'll just change the way I authenticate on remotes.

**Comment by dirk-thomas** [comment]
I will mark this as "wontfix" since I don't intend to work on this. If someone can come up with a pull request implementing this somehow I would be more than happy to review and integrate it.

**Comment by mhubii** [comment]
would be nice to have that feature

**Comment by dirk-thomas** [comment]
> would be nice to have that feature

Please feel free to contribute a pull request.

**Comment by mhubii** [comment]
Do you have recommendations where to start?

**Comment by mhubii** [comment]
hotfix is to call

```
vcs import < yaml_file.repos --workers=1
```

**Comment by dirk-thomas** [comment]
I added docs about the `--workers` option and its effect on `stdin` processing: #119.

> So maybe one has to stop the execution of additional workers if `subprocess.communicate` in `VcsClientBase`

While executing all the commands sequentially that would also mostly prohibit the performance improvements achieved by multiple workers. So I don't see it being a viable alternative to `--workers 1`. Unfortunately I don't have a suggestion for you.
