### ISSUE TITLE
Issue with Parallel Worker Threads and Private Repos

### ISSUE THREAD

**Issue by micat001** [dirk-thomas/vcstool#238]
I'm seeing an issue with using the default number of workers while trying to import 5 private repos.

Specifically if I leave the ```--workers``` flag at the default and I use "abcdef" as a username and "password" as my password, I'll see this:

![vcs_err_multiple_workers](https://user-images.githubusercontent.com/97049012/160194437-849f3a03-4a66-49fd-88ac-9e94ab49f1ba.png)

My password credentials end up jumbled into the login credentials. 
Because of this, I can never finish the import. This seemed like a threading issue to me so I checked and with the same import command but a single worker, the import works:
![vcs_err_single_worker](https://user-images.githubusercontent.com/97049012/160191172-fa8272fc-481f-429b-a8d8-213f79db586b.png)

I've replicated this issue on two different computers. Although I'm not interested in sharing the repos I'm working on for obvious reasons, I wonder if the issue can be recreated by others using private repos (at least 5). 

Wondering if this is expected/known behavior of the library. Thanks!

**Comment by dirk-thomas** [comment]
This is documented on the starting page of this repository: https://github.com/dirk-thomas/vcstool#parallelization-and-stdin

**Comment by micat001** [comment]
Oh wow,duh. I dug through the issues but not the readme. Closing.

**Comment by zymouse** [comment]
## GIT certificate
This is a git problem: use git credentials to avoid typing your username and password multiple times over!
```bash
# Open credentials Clear cached credentials after 300 seconds [5min]
git config --global credential.helper 'cache --timeout=600'
```
Once you've configured the cache credentials helper, the next time you clone, pull, or push to a remote repository over HTTPS, Git will ask you for a username and password. Once entered, these credentials will be cached for a specified amount of time. During this time, you don't need to re-enter your credentials.

## Test Cases
I have over a dozen private libraries here, all downloaded perfectly using GIT credentials!
