### ISSUE TITLE
`export` should strip the `src` path element

### ISSUE THREAD

**Issue by gerkey** [dirk-thomas/vcstool#24]
Generally, when working with `vcs`, my working directory contains a subdirectory called `src` and all the actions I take operate on the contents of `src` without me referring to it explicitly.

But when I `vcs export` to capture the state of my source tree, if I do it from above `src`, then the local paths that are produced start with `src/`. If I subsequently `vcs import` that result somewhere else in the normal way, I end up with the checkout going into `src/src/`.

To get what I consider to be the right answer, I have to run `vcs export` inside `src`. It seems to me that running `vcs export` at the top should give me the local paths without the leading `src/` path element.

I'm happy to make a PR to implement the change, but I first want to confirm that I have the right perspective.

**Comment by dirk-thomas** [comment]
`vcs` stores the exact relative paths you point it to. And also restores exactly the structure as stored in the yaml. It doesn't know about `src` and doesn't treat it any special.

You should invoke it with whatever base path you like to use. The default if not specified is the current path.

**Comment by gerkey** [comment]
Oh, I thought that `vcs` treats `src` specially. Then do `vcs pull` and friends just recursively crawl the whole tree looking for things that appear to be repos?

**Comment by dirk-thomas** [comment]
Yes

**Comment by gerkey** [comment]
Ah, thanks. I mistook a common pattern for a special work flow. Never mind.
