### ISSUE TITLE
Can't import tarballs

### ISSUE THREAD

**Issue by bbaillio** [dirk-thomas/vcstool#25]
In the README.rst is mentions that tar is supported as a pseudo client, to fetch a tarball at a URL and extract it.
When I try to use the tool for this, it always fails with the following error:
`Invocation of command 'import' on client 'tar' failed: TypeError: initial_value must be str or None, not bytes (/usr/lib/python3/dist-packages/vcstool/clients/tar.py:72)`

I went in and tinkered with the tar.py file and changed the StringIO fileobj on the tarfile.open to be a BytesIO. This had the affect of making the script happy, and printing out that my tarball was extracted, but there's no data anywhere. I can't find the contents of the tarball where it is expected to be.

**Comment by bbaillio** [comment]
My .repos file looks like this:
repositories:
    vision:
        type: tar
        url: https://url-to-my-tarball/myfile.tar
        version: master

and I just do `vcs import . < my.repos`

**Comment by dirk-thomas** [comment]
Thank you for the report. I was able to reproduce the problem with Python 3 and have fixed it in 8da159df04d1e52d31251e5688576e5e2acdd29f. You can either wait for the next release to become available or apply this patch to the installed file `/usr/lib/python3/dist-packages/vcstool/clients/tar.py`.
