### ISSUE TITLE
Credential input broken when importing multiple repos

### ISSUE THREAD

**Issue by mocudev** [dirk-thomas/vcstool#26]
When importing multiple repos that require username/password, it will ask for multiple usernames on the same line and everything will get out of wack.

This seems to be fixed by passing -w 1 to the import command to make it only use 1 thread. Can 1 thread be changed to be default?

**Comment by dirk-thomas** [comment]
This looks like a duplicate of #23. If you agree please close the ticket. Otherwise please consider providing a PR to add support for `stdin` handling.

**Comment by mocudev** [comment]
Yes, looks like a duplicate, I'll see if I can figure out a better way to handle stdin, though it does work fine if there is only 1 worker thread.

**Comment by dirk-thomas** [comment]
The next version will allow to specify the number of worker threads on the command line. See 89b92b9ec03dc0a766e8e1d06203ac03dcc8546d

**Comment by mocudev** [comment]
Yeah, using -w 1 fixes it, that's why I was asking for that to be the default at least for import. I'll take a look and see if there is a way to fix it with mutexes or something. The issue seems to be from the multiple git workers clobbering eachothers stdout.

**Comment by dirk-thomas** [comment]
Imo the common case is that users doesn't enter the credentials manually everytime. And in that case the performance improvement of using multiple worker threads is significant.
