### ISSUE TITLE
Ignore self signed cert for a specific repository

### ISSUE THREAD

**Issue by firesurfer** [dirk-thomas/vcstool#268]
Hi, we are hosting our own gitlab and use git-lfs for some repositories. Git-lfs uses https with Gitlab. As we use a self-signed certificate we need to tell git for this specific repository to ignore the cert. 
What we currently do is: `GIT_SSL_NO_VERIFY=true git clone /git pull`

Would it be possible to specify specific git argument in the `repos.list`?

**Comment by christophebedard** [comment]
Have you tried doing `GIT_SSL_NO_VERIFY=true vcs import ...`?

**Comment by firesurfer** [comment]
This does definitely work. But disabling SSL verify  for all repositories in a workspace is something I would like to avoid.
It would be nice if it would be possible to specify that on a per repository basis in the repos.list.

The solution I went with now (which is probably also preferable) is to add our self signed root cert to the trusted certificates of the system:

```
cp cert.crt /usr/local/share/ca-certificates
update-ca-certificates
```

**Comment by christophebedard** [comment]
> But disabling SSL verify for all repositories in a workspace is something I would like to avoid.

Definitely.

> The solution I went with now (which is probably also preferable) is to add our self signed root cert to the trusted certificates of the system:

That's probably the right solution, yeah. `vcstool` is in no/low maintenance mode (see #242), so I doubt a feature like this would be merged anyway.

**Comment by firesurfer** [comment]
> That's probably the right solution, yeah. vcstool is in no/low maintenance mode (see https://github.com/dirk-thomas/vcstool/issues/242), so I doubt a feature like this would be merged anyway.

That a pity to hear given that `vcstool` is an important building block of the ros2 ecosystem.


I just summarize possible solutions if someone else stumbles upon this issue:

1. Install your self signed root certificate to the system (preferable) 
See https://ubuntu.com/server/docs/security-trust-store

2. Solutions which disable ssl verify - __unsecure__ :

a ) Prepend `GIT_SSL_NO_VERIFY=true`  to your git commands
b) Disable ssl verification for a specific already cloned repository. Run `git config http.sslVerify false` in the repository

If you have just one or two repositories that struggle with ssl I suggest you clone them manually into your workspace for by using method a).
