### ISSUE TITLE
Ubuntu 12.04 no longer supported?

### ISSUE THREAD

**Issue by dustingooding** [dirk-thomas/vcstool#28]
I installed a new 12.04.5 Deskop system (supporting an aging robot configuration) and set up the ROS Precise apt repo.

    $ sudo apt-get install python-vcstool
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     python-vcstool : Depends: python:any (>= 2.7.5-5~)
    E: Unable to correct problems, you have held broken packages.

AFAIK, 12.04.5 isn't going to get Python 2.7.5.   It's stuck at:

    $ python --version
    Python 2.7.3

Can the python-vcstool package in the ROS Precise apt repo be rolled back?  Is version `2.7.5-5~` actually required, or is that an artifact of a build server decision?  Or can you recommend a workaround?

**Comment by dustingooding** [comment]
Looks like the pip package installs and works.  I'm betting it's just a Debian packaging issue.

**Comment by dirk-thomas** [comment]
Thanks for pointing out the problem on Precise.

The Debian packages are not built by any build server but using the script from https://github.com/ros-infrastructure/ros_release_python which uses `stdeb`. It seems like that the Debian package embeds this Python version (done on Xenial using `stdeb` from Debian) which it didn't do before (on Trusty using `stdeb` from PIP). The following documentation update should prevent future problems: ros-infrastructure/ros_release_python#13

I have also released a new version of `vcstool` (0.1.17) with this updated process and it has the correct Python dependencies as far as I can see in the Debian control file. If you could please try it and confirm that it works for you too that would be great.
