### ISSUE TITLE
importing more than 20 repos causes fails

### ISSUE THREAD

**Issue by tkelestemur** [dirk-thomas/vcstool#30]
Hi, I am using latest version of the vcstool (0.1.20).
I have a YAML file consisting more than 35 repos. When I try importing repos to a single folder after 20~ repos it is throwing errors and stuck downloading next repos. I have tried splitting YAML file to 3 different files and running them in order to same folder. Every one of them has around 12 repos. First one goes without problem but second one either throws error or stuck downloading. I am able to clone all the repos manually meaning that there is no permission issue.

I get something like this : 
`.....................EE..EE....`

**Comment by dirk-thomas** [comment]
The tool is actively being used to handle sets of many more repos then 20. Therefore I doubt the title is accurately describing the problem.

Please provide more information. When you clone the repos manually are you being prompted to enter credentials? What is the output for the failing repos? Can you share the repositories file which is problematic for you?

**Comment by tkelestemur** [comment]
I am aware it can handle more then 20 repos, I was using before and there was no problem.

No, since I have generated ssh-keys, it doesn't ask me credentials. Unfortunately I cannot share them because all of them are private repositories but I have tried same YAML file on my Macbook and it has the same problem. I am using Ubuntu 14.04 desktop. Since it stucks waiting for next repo I couldn't see any failing output. I've tried --debug but it didn't show me anything either.

**Comment by dirk-thomas** [comment]
Without further details it will be difficult to narrow down the reason. Have you updated the version of `vcstool` since it worked before? Or have you added additional repos to the list since then? Can you try to narrow down the problem. It seems most of the repos in your file work fine and only one or a few are causing the problem. You can e.g. run `vcs import` with the option `-w 1` to avoid parallel operations to narrow down which single repo is causing the trouble. Or you can manually bisect the set.

**Comment by tkelestemur** [comment]
I've tried `-w 1` but again no luck. Yeah, I've upgraded vcstool but did not add any new repo.  I am pretty sure that every repo is OK, I can clone them manually. I've split the YAML file to 3 different files and tried again but didn't work. It is really weird.

**Comment by dirk-thomas** [comment]
Can you please try to split it further up to the extreme case of having only one entry per file.

**Comment by dirk-thomas** [comment]
If you install the latest master branch passing `--debug` will output the progress of the various jobs. That will tell you which repository is "hanging" (or just taking very long).

**Comment by dirk-thomas** [comment]
Did you have a change to narrow down the problem and/or use the new debug information to investigate on which repo the command is hanging?

**Comment by tkelestemur** [comment]
Hello, we still couldn't find a way narrow down the problem. We suspect it is a network problem rather than a bug.

**Comment by dirk-thomas** [comment]
As mentioned the new debug output should tell you exactly which repository is hanging. I agree that a network related issue is now likely from what I know.

I will close the ticket for now but please feel free to comment with more information when available and this can be reopened.
