### ISSUE TITLE
Submodule transition support

### ISSUE THREAD

**Issue by compiaffe** [dirk-thomas/vcstool#33]
vcs status does not show any output for submodules inside a git repository.

I am not quite sure if this is intended behaviour, but vcs could still be a helpful tool for managing the submodules.

**Comment by dirk-thomas** [comment]
Can you clarify for which verbs you would like to see support for submodules? What do you mean with "transition" in the ticket title?

**Comment by compiaffe** [comment]
Transition referred to transitioning from the use of submodules to vcs.

I would like to see vcs status mainly, but push and pull (maybe with flag to include the submodules) would be helpful, too.

**Comment by dirk-thomas** [comment]
I am not sure I understand yet completely. Can you please describe some examples in detail what `git` command you expect to be run for a specific invocation of `vcs`.

**Comment by dirk-thomas** [comment]
I am not sure I understand yet completely. Can you please describe some examples in detail what `git` command you expect to be run for a specific invocation of `vcs`. `vcs status` should show the same information as `git status` which afaik should include information about submodules.

**Comment by dirk-thomas** [comment]
I will close this for now since it is still unclear what the expected behavior is. Please feel free to comment with the requested information and this can be reopened.
