### ISSUE TITLE
[feature] Make vcs status --hide show when branch diverged from their remote

### ISSUE THREAD

**Issue by mikaelarguedas** [dirk-thomas/vcstool#35]
If it is of any interest I can try to take a shot at it. For the [git client](https://github.com/dirk-thomas/vcstool/blob/master/vcstool/clients/git.py#L327-L340) for example, we could apply something like:
```python
-            cmd = [GitClient._executable, 'status', '-s']
+            cmd = [GitClient._executable, 'status', '-s', '-b']
             if command.quiet:
                 cmd += ['--untracked-files=no']
             result = self._run_command(cmd)
-            if result['returncode'] or not result['output']:
+            if result['returncode'] or ('\n' not in result['output'] and 'ahead' not in result['output'] and 'behind' not in result['output']):
+                result['output'] = ''
```
Not sure how it would work for locales though. Didn't look at other vcs systems to see if something similar can be done easily

**Comment by dirk-thomas** [comment]
I have created PR #36 to implement this improved behavior without relying on the output. It would be great if you could try the modified version from source and report if it addresses your use case.

**Comment by mikaelarguedas** [comment]
Tried with all the cases I use status --hide:
 - unstaged changes
 - staged changes
 - ahead
 - behind
 - diverged (ahead and behind)

Works fine for all cases :+1: :tada: thanks!
