### ISSUE TITLE
vcs import hangs if environment variables are in the --input path

### ISSUE THREAD

**Issue by jlack1987** [dirk-thomas/vcstool#43]
We use `vcstool` in our CI server to clone repos files with lines like,
```bash
vcs import --input $CI_PROJECT_DIR/repos_file.repos $MY_WORKSPACE/src
```
This has been working fine for us until yesterday. Now it hangs on any import lines where there are environment variables in the paths. I also see there might have been an update yesterday? This is all going on in a docker, but I can confirm that the docker is using `vcs 0.1.26`.

Edit: Can also confirm that on another computer trying the same thing with `vcs 0.1.22` that it has no problem with environment variables in the args.

Edit+: Can also (unsurprisingly)show that it's not actually the environment variables causing the problem. With valid manually entered paths I can make it hang. I know this doesn't really help much, but the line i'm using is,
```
vcs import --input /builds/DD/repos_dir/repos_file.repos /builds/DD/deps_ws/src
```

Edit++: If I modify the `path` arg to be `.` then it works, so I guess it's something with the way it's handling the `path` arg

Edit+++: Sorry for all the edits, just trying to provide as much info as possible, but I think I have shown that if the `path` arg is any absolute path then it hangs. Tried to import to `/tmp` and it hung(was in a docker, so I was `root`).

**Comment by dirk-thomas** [comment]
As you already mentioned the environment variables can't make a difference. Simply because they are being evaluated by the shell. The script `vcs` only gets the resolved result arguments.

I have tried to reproduce the problem but couldn't so far. Can you please share a `.repos`. file with which you can reproduce the problem. Can you please also mention if you are using the Python 2 or Python 3 version of the package. Have you tried running the `import` command without multiple workers (by passing `----workers 1`)?

**Comment by dirk-thomas** [comment]
Never mind - I think I found the problem. Looking into making a fix...

**Comment by dirk-thomas** [comment]
#44 fixed the regression.The latest version 0.1.27 contains the fix. Depending on where you fetch this package from it might take a bit to appear in the public repos / mirrors.

**Comment by dirk-thomas** [comment]
Thank you for reporting the problem so quickly!

**Comment by kensley** [comment]
Thanks for the rapid fix Dirk. Is there a unit test we can add to test this?

**Comment by dirk-thomas** [comment]
Currently this package doesn't have any tests (beside flake8). It would certainly be good to add as this example has demonstrated.

**Comment by jlack1987** [comment]
Can at least confirm that this does fix the issue
