### ISSUE TITLE
ZIP file support

### ISSUE THREAD

**Issue by BrannonKing** [dirk-thomas/vcstool#48]
Please add a handler for zip files (similar to the tar file handler). Thanks.

**Comment by dirk-thomas** [comment]
Would you be interested in providing a PR for this feature? It should be fairly similar to the existing tar handler.

**Comment by dirk-thomas** [comment]
@BrannonKing Please see PR # which implements support for zip files. It would be great if you could try the proposed patch and comment if it works for your use case.

**Comment by dirk-thomas** [comment]
@BrannonKing Please see PR #51 which implements support for zip files. It would be great if you could try the proposed patch and comment if it works for your use case.
