### ISSUE TITLE
Allow vcs import to apply patches specified in a URL

### ISSUE THREAD

**Issue by scpeters** [dirk-thomas/vcstool#62]
This could be used for adding `package.xml` files after clone a repository that doesn't have them (such as gazebo or sdformat).

**Comment by dirk-thomas** [comment]
I am not sure if this needs / should be a feature provided by `vcstool`. Can you describe how you imagine the workflow and where the actual patches are coming from?

As far as I understand your use case I think a better approach to this is to keep the metadata separate from the repository (if upstream doesn't want to place them into the repo in the first place). E.g. [this repository](https://github.com/colcon/colcon-metadata-repository) provides the additional metadata necessary to build Gazebo (at least a couple of weeks ago) with a prototype of the new [universal build tool](http://design.ros2.org/articles/build_tool.html).

**Comment by scpeters** [comment]
Interesting. I'll take a look at colcon.

Patching is extra complexity that you may not want for this tool. I mentioned it because debian and homebrew support patches, but the headaches could easily outweigh the benefits.

**Comment by dirk-thomas** [comment]
> I'll take a look at colcon.

Currently only the referenced metadata repository if public. The other repos related to `colcon` aren't yet.
