### ISSUE TITLE
python3-setuptools is a dependency

### ISSUE THREAD

**Issue by russkel** [dirk-thomas/vcstool#64]
When using on a fresh debian (or armbian in my case) install I get an error:
```
Traceback (most recent call last):
  File "/usr/bin/vcs", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```
This is resolved by `apt-get install python3-setuptools`. Perhaps this should be added to the dependencies of the python3-vcstools package?

**Comment by dirk-thomas** [comment]
Thank you for reporting the problem. #65 should address the problem.
