### ISSUE TITLE
Export tags?

### ISSUE THREAD

**Issue by murrdpirate** [dirk-thomas/vcstool#98]
I have a bunch of repos that are all checked out to a git tagged release. When I export my workspace, the versions are all recorded as git hashes. I didn't see a way to export the tag instead. I'd like the tagged release so I can more easily understand how packages are being updated. Is this possible?

**Comment by dirk-thomas** [comment]
Until now that was not possible. Please try the patch from #100 which should reference the tag name if there is exactly one tag referencing the current hash.
